---
# We collect all zones currently configured on the server
- name: get all configured zones from server
  find:
    paths: "{{ _ansible_managed_zones_dir }}"
  register: _dns_ansible_zones

# In case a zone is no longer in the list of active zones, we will remove the
# files from the server (and later tasks will also remove it from the config).
- name: remove zonefiles from server when zone is no longer active
  include_tasks: __zoneremove.yml
  loop: "{{ _dns_ansible_zones.files }}"
  loop_control:
    label: "{{ item.path|basename|replace('.dnszone','') }}"
  vars:
    _remove_dns_zone: "{{ item.path|basename|replace('.dnszone','') }}"
  when: item.path|basename|replace('.dnszone','') not in _dns_zones_active

